from fpdf import FPDF
import os

# ... (Keep your PDF Class header/footer methods same as before) ...
class PDF(FPDF):
    def header(self):
        self.set_draw_color(79, 172, 254) 
        self.set_line_width(1)
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, 'CYBERX SYNTHETIC AUDITOR // INTERNAL USE ONLY', 0, 0, 'R')
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

# --- UPDATED FUNCTION SIGNATURE ---
def generate_report(findings, ai_analyses, chart_path=None, attack_path_summary=None, filename="report.pdf"):
    pdf = PDF(orientation='P', unit='mm', format='A4')
    pdf.set_margins(25, 25, 25)
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()
    
    # --- TITLE ---
    pdf.set_font("Helvetica", 'B', 24)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 10, "Security Audit Report", 0, 1, 'L')
    pdf.set_font("Helvetica", '', 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, "Generated by CyberX Local Digital Twin", 0, 1, 'L')
    pdf.ln(5)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(25, pdf.get_y(), 185, pdf.get_y())
    pdf.ln(10)

    # --- EXECUTIVE SUMMARY ---
    pdf.set_font("Helvetica", 'B', 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Executive Summary", 0, 1)
    
    # --- NEW: ATTACK PATH SECTION ---
    if attack_path_summary:
        pdf.set_font("Helvetica", 'B', 12)
        pdf.set_text_color(192, 57, 43) # Dark Red for Strategy
        pdf.cell(0, 10, "Strategic Threat Analysis (AI Generated):", 0, 1)
        
        pdf.set_font("Times", '', 11)
        pdf.set_text_color(50, 50, 50)
        pdf.multi_cell(0, 6, attack_path_summary)
        pdf.ln(5)

    # --- NEW: CHART SECTION ---
    if chart_path and os.path.exists(chart_path):
        # Center the image. A4 width is 210mm.
        # Image width 100mm. Margin is 25mm.
        # X = (210 - 100) / 2 = 55
        pdf.image(chart_path, x=55, w=100)
        pdf.ln(5)
    
    pdf.set_font("Times", '', 12)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 7, "This report contains a detailed analysis of network vulnerabilities detected in the target environment.")
    pdf.ln(10)

    # --- FINDINGS LOOP ---
    for i, finding in enumerate(findings):
        pdf.set_font("Helvetica", 'B', 14)
        pdf.set_text_color(0, 0, 0)
        pdf.write(10, f"{i+1}. {finding['title']} ")
        
        severity = finding['severity'].upper()
        if severity == "CRITICAL":
            pdf.set_text_color(220, 53, 69)
        elif severity == "HIGH":
            pdf.set_text_color(253, 126, 20)
        elif severity == "MEDIUM":
            pdf.set_text_color(255, 193, 7)
        else:
            pdf.set_text_color(40, 167, 69)
            
        pdf.set_font("Helvetica", 'B', 10)
        pdf.write(10, f" [{severity}]")
        pdf.ln(8)
        
        pdf.set_font("Courier", '', 10)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(0, 6, f"Target Host: {finding['host']}", 0, 1)
        pdf.ln(2)
        
        pdf.set_font("Helvetica", 'B', 11)
        pdf.set_text_color(44, 62, 80)
        pdf.cell(0, 8, "Contextual AI Analysis:", 0, 1)
        
        pdf.set_font("Times", '', 11)
        pdf.set_text_color(30, 30, 30)
        analysis_text = ai_analyses[i]
        pdf.multi_cell(0, 6, analysis_text)
        pdf.ln(10)

    output_path = f"data/output/{filename}"
    pdf.output(output_path)
    return output_path